import { Agent } from './types';

export const AGENTS: Agent[] = [
  {
    id: 'nebula',
    name: 'Nebula',
    slug: 'nebula',
    emoji: '\u2728',
    color: '#a78bfa',
    description: 'Central orchestrator - routes tasks to specialist agents',
    status: 'active',
    lastAction: 'Coordinating agent swarm',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'github-agent',
    name: 'GitHub Agent',
    slug: 'github-agent',
    emoji: '\ud83d\udc19',
    color: '#f0abfc',
    description: 'Manages repos, PRs, issues, and code reviews',
    status: 'idle',
    lastAction: 'Waiting for tasks',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'code-agent',
    name: 'Code Agent',
    slug: 'code-agent',
    emoji: '\ud83d\udcbb',
    color: '#67e8f9',
    description: 'Executes Python, Bash, and TypeScript in sandboxed environments',
    status: 'idle',
    lastAction: 'Sandbox ready',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'gmail-agent',
    name: 'Gmail Agent',
    slug: 'gmail-agent',
    emoji: '\ud83d\udce7',
    color: '#fca5a5',
    description: 'Reads, sends, and manages email through Gmail',
    status: 'idle',
    lastAction: 'Inbox synced',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'slack-agent',
    name: 'Slack Agent',
    slug: 'slack-agent',
    emoji: '\ud83d\udcac',
    color: '#86efac',
    description: 'Sends messages and monitors Slack channels',
    status: 'idle',
    lastAction: 'Channels monitored',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'notion-agent',
    name: 'Notion Agent',
    slug: 'notion-agent',
    emoji: '\ud83d\uddd2',
    color: '#fdba74',
    description: 'Manages Notion pages, databases, and workspace',
    status: 'idle',
    lastAction: 'Workspace connected',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'twitter-agent',
    name: 'Twitter Agent',
    slug: 'twitter-agent',
    emoji: '\ud83d\udc26',
    color: '#7dd3fc',
    description: 'Posts tweets and monitors Twitter/X activity',
    status: 'idle',
    lastAction: 'Feed monitored',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'calendar-agent',
    name: 'Calendar Agent',
    slug: 'calendar-agent',
    emoji: '\ud83d\udcc5',
    color: '#fde68a',
    description: 'Manages Google Calendar events and scheduling',
    status: 'idle',
    lastAction: 'Calendar synced',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'linear-agent',
    name: 'Linear Agent',
    slug: 'linear-agent',
    emoji: '\ud83d\udcca',
    color: '#c4b5fd',
    description: 'Tracks issues and projects in Linear',
    status: 'idle',
    lastAction: 'Projects loaded',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'discord-agent',
    name: 'Discord Agent',
    slug: 'discord-agent',
    emoji: '\ud83c\udfae',
    color: '#a5b4fc',
    description: 'Manages Discord server messages and bots',
    status: 'idle',
    lastAction: 'Server connected',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'telegram-agent',
    name: 'Telegram Agent',
    slug: 'telegram-agent',
    emoji: '\u2708\ufe0f',
    color: '#5eead4',
    description: 'Sends and receives Telegram messages',
    status: 'idle',
    lastAction: 'Bot online',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'facebook-agent',
    name: 'Facebook Agent',
    slug: 'facebook-agent',
    emoji: '\ud83d\udc4d',
    color: '#93c5fd',
    description: 'Manages Facebook pages and posts',
    status: 'idle',
    lastAction: 'Page connected',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
];
