import { Agent } from './types';

export const AGENTS: Agent[] = [
  {
    id: 'nebula',
    name: 'Nebula',
    slug: 'nebula',
    emoji: '\u2728',
    color: '#a78bfa',
    description: 'Central AI orchestrator \u2014 routes tasks, coordinates agents, manages workflows and automations across the entire swarm.',
    status: 'active',
    lastAction: 'Orchestrating swarm operations',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'code-agent',
    name: 'Code Agent',
    slug: 'code-agent',
    emoji: '\ud83d\udcbb',
    color: '#67e8f9',
    description: 'Executes Python, Bash, and TypeScript in a secure cloud sandbox with pandas, numpy, matplotlib, and more.',
    status: 'idle',
    lastAction: 'Sandbox ready',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'web-agent',
    name: 'Web Agent',
    slug: 'web-agent',
    emoji: '\ud83c\udf10',
    color: '#34d399',
    description: 'Scrapes web pages, extracts structured data, and automates browser interactions via accessibility snapshots.',
    status: 'idle',
    lastAction: 'Browser standby',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'media-agent',
    name: 'Media Agent',
    slug: 'media-agent',
    emoji: '\ud83c\udfa8',
    color: '#f472b6',
    description: 'Transcribes audio (Whisper), analyzes images (GPT-4o), generates/edits images (Gemini), and text-to-speech.',
    status: 'idle',
    lastAction: 'Media pipeline ready',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'inbox-agent',
    name: 'Inbox Agent',
    slug: 'inbox-agent',
    emoji: '\ud83d\udce8',
    color: '#fb923c',
    description: 'Sends emails via joshua-daquipil@nebula.me, reads inbox, waits for replies, and manages trusted senders.',
    status: 'idle',
    lastAction: 'Inbox synced',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'agent-creator',
    name: 'Agent Creator',
    slug: 'agent-creator',
    emoji: '\ud83e\uddea',
    color: '#c084fc',
    description: 'Creates custom AI agents with API integrations, tools, and skills. Builds new specialized agents on demand.',
    status: 'idle',
    lastAction: 'Ready to build',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'pr-monitor',
    name: 'PR Monitor',
    slug: 'pr-monitor',
    emoji: '\ud83d\udd0d',
    color: '#4ade80',
    description: 'Scans GitHub for PRs needing review, stale PRs, merge conflicts, and failing CI. Delivers smart summaries.',
    status: 'idle',
    lastAction: 'Monitoring PRs',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'github-repo-manager',
    name: 'GitHub Manager',
    slug: 'github-repo-manager',
    emoji: '\ud83d\udc19',
    color: '#e879f9',
    description: 'Full GitHub agent for joshua17574 \u2014 manages repos, branches, PRs, issues, commits, and Actions workflows.',
    status: 'idle',
    lastAction: 'Repos synced',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'kwen-net-page-manager',
    name: 'Kwen Net Manager',
    slug: 'kwen-net-page-manager',
    emoji: '\ud83d\udcf1',
    color: '#60a5fa',
    description: 'Manages the Kwen Net Facebook Page \u2014 creates posts, replies to comments, handles inbox, checks insights.',
    status: 'idle',
    lastAction: 'Page monitored',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'google-drive-manager',
    name: 'Drive Manager',
    slug: 'google-drive-manager',
    emoji: '\ud83d\udcc1',
    color: '#fbbf24',
    description: 'Manages Google Drive for joshua.daquipil0817@gmail.com \u2014 uploads, downloads, searches, shares, organizes files.',
    status: 'idle',
    lastAction: 'Drive connected',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'spotify-music-manager',
    name: 'Spotify Manager',
    slug: 'spotify-music-manager',
    emoji: '\ud83c\udfb5',
    color: '#22c55e',
    description: 'Manages your Spotify \u2014 searches tracks, creates playlists, controls playback, fetches recommendations.',
    status: 'idle',
    lastAction: 'Spotify connected',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'x-twitter-engagement-agent',
    name: 'X/Twitter Agent',
    slug: 'x-twitter-engagement-agent',
    emoji: '\ud835\udd4f',
    color: '#f8fafc',
    description: 'Manages your X presence \u2014 posts tweets, monitors mentions, engages with content, searches trending topics.',
    status: 'idle',
    lastAction: 'Feed monitored',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'google-drive-file-manager',
    name: 'Drive File Manager',
    slug: 'google-drive-file-manager',
    emoji: '\ud83d\udcc2',
    color: '#facc15',
    description: 'Manages files and folders on Google Drive for joshua.daquipil0817@gmail.com \u2014 uploads, downloads, searches, organizes, and shares files via OAuth.',
    status: 'idle',
    lastAction: 'Drive synced',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'telegram-notifier',
    name: 'Telegram Notifier',
    slug: 'telegram-notifier',
    emoji: '\ud83d\udce9',
    color: '#38bdf8',
    description: 'Real-time Telegram notification hub for Joshua (@joshua761) \u2014 sends formatted alerts, task completions, error reports, and daily/weekly summaries.',
    status: 'idle',
    lastAction: 'Telegram connected',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'research-intelligence-agent',
    name: 'Research Agent',
    slug: 'research-intelligence-agent',
    emoji: '\ud83d\udcca',
    color: '#818cf8',
    description: 'Deep research specialist \u2014 performs multi-source web research and produces structured intelligence briefs on trending topics, competitive analysis, and fact-checking.',
    status: 'idle',
    lastAction: 'Research standby',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'content-strategist-agent',
    name: 'Content Strategist',
    slug: 'content-strategist-agent',
    emoji: '\ud83d\udcdd',
    color: '#f9a8d4',
    description: 'Coordinates cross-platform content strategy for YouTube Shorts, Twitter/X, and Kwen Net Facebook Page \u2014 generates weekly content calendars and post schedules.',
    status: 'idle',
    lastAction: 'Strategy loaded',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
  {
    id: 'youtube-shorts-creator',
    name: 'YouTube Shorts Creator',
    slug: 'youtube-shorts-creator',
    emoji: '\ud83c\udfac',
    color: '#ef4444',
    description: 'Produces complete YouTube Shorts from script JSON \u2014 runs the v3.0 factory (TTS narration, cinematic animations, video composition) and uploads to YouTube.',
    status: 'idle',
    lastAction: 'Factory ready',
    lastActionTime: Date.now(),
    taskCount: 0,
  },
];
